package view;

public enum TelasEnum {

    LOGIN(),
    PRINCIPAL_CLIENTE(), COMPRA_FICHAS(), VISUALIZAR_DADOS(), PAGAMENTO(),
    PRINCIPAL_VENDEDOR(), VENDA(), LISTAR_REFEICOES(), PAGAMENTOVENDEDOR(), VENDA_CLIENTE(), PAGAMENTO_VENDA_CLIENTE(),
    PRINCIPAL_GERENTE(), LISTAR_USUARIO(), CADASTRAR_USUARIO(), ALTERAR_USUARIO(), LISTAR_REGISTRO_COMPRA(), CADASTRAR_CARDAPIO(),
    LISTAR_CARDAPIOS(), ALTERAR_CARDAPIO(), FILTRAR_USUARIO(), FILTRAR_CARDAPIO(), FILTRAR_REGISTRO(), HISTORICO_COMPRAS(), FILTRO_HISTORICO(),
    VISUALIZAR_REFEICOES(), CADASTRAR_REFEICOES(), ALTERAR_REFEICOES(), VISUALIZAR_CARDAPIOS(), LISTAR_ENTRADAS(), CATRACA(), CALENDARIO()
}
