package view;

public enum TelasEnum {

    LOGIN(),
    PRINCIPAL_CLIENTE(), COMPRA_FICHAS(), VISUALIZAR_DADOS(),
    PRINCIPAL_VENDEDOR(), VENDA(), LISTAR_REFEICOES(),
    PRINCIPAL_GERENTE(), LISTAR_USUARIO(), CADASTRAR_USUARIO(), ALTERAR_USUARIO(), LISTAR_REGISTRO_COMPRA(), CADASTRAR_CARDAPIO(),
    VISUALIZAR_REFEICOES(), CADASTRAR_REFEICOES(), ALTERAR_REFEICOES(), VISUALIZAR_CARDAPIOS()
}
